<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SQA20195" failures="0" tests="1" name="RunnerFile.RunnerClass" time="54.013" errors="1" timestamp="2020-11-17T11:46:42 GMT" skipped="0">
  <testcase classname="RunnerFile.RunnerClass" name="feature" time="54.013">
    <error message="java.nio.file.FileSystemException: \\sqa-hanfs1\Information Systems\Operations\Application Solutions\Software Development\Quality Assurance\Projects\CAF ADMIN\CLC-Exemptions\Test-Data\CLC_Exemptions_NEW.csv: The network path was not found.
" type="cucumber.runtime.CucumberException">
      <![CDATA[cucumber.runtime.CucumberException: java.nio.file.FileSystemException: \\sqa-hanfs1\Information Systems\Operations\Application Solutions\Software Development\Quality Assurance\Projects\CAF ADMIN\CLC-Exemptions\Test-Data\CLC_Exemptions_NEW.csv: The network path was not found.

at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.nio.file.FileSystemException: \\sqa-hanfs1\Information Systems\Operations\Application Solutions\Software Development\Quality Assurance\Projects\CAF ADMIN\CLC-Exemptions\Test-Data\CLC_Exemptions_NEW.csv: The network path was not found.

at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
at java.base/java.nio.file.Files.newInputStream(Files.java:155)
at java.base/java.nio.file.Files.newBufferedReader(Files.java:2838)
at java.base/java.nio.file.Files.newBufferedReader(Files.java:2870)
at PageObjects.CLCInvoiceExemptions.readCSV(CLCInvoiceExemptions.java:66)
at StepDefinition.CLC_StepDefinition.the_user_chooses_the_CSV_file_to_load(CLC_StepDefinition.java:25)
at âœ½.When The user chooses the CSV file to load(ExExtriesFeature.feature:16)
]]>
    </error>
  </testcase> <!-- feature -->
  <system-out>
_____________________________________________________________________ <p>  </system-out>
</testsuite> <!-- RunnerFile.RunnerClass -->
